---
# https://docs.ansible.com/ansible/latest/modules/set_fact_module.html
- name: Get the simplified major.minor version string
  set_fact:
    version_simple: "{{ elasticsearch.version | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') }}"

# https://docs.ansible.com/ansible/latest/modules/include_vars_module.html
- name: Include defaults for configuration, per the installed version.
  include_vars:
    file: main-{{ version_simple }}.yml

# http://docs.ansible.com/ansible/latest/set_fact_module.html
- name: Merge elasticsearch_default and elasticsearch variables
  set_fact:
    elasticsearch_combined: "{{ elasticsearch_defaults | combine(elasticsearch, recursive=True) }}"

# Include OS-specific installation tasks.
- include_tasks: setup-RedHat.yml
  when:
    - ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when:
    - ansible_os_family == 'Debian'



- name: Change Elasticsearch's memory usage
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: "^-Xms"
    line: "-Xms{{ elasticsearch_combined.memory_usage }}m"
    state: present
- name: Change Elasticsearch's memory usage
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: "^-Xmx"
    line: "-Xmx{{ elasticsearch_combined.memory_usage }}m"
    state: present

- name: Set the open file limits
  pam_limits:
    domain: '*'
    limit_item: nofile
    limit_type: hard
    value: '65536'
  when:
    - elasticsearch_combined.set_ulimits

# http://docs.ansible.com/ansible/latest/template_module.html
- name: Copy config file
  template:
    src: "elasticsearch-{{ version_simple }}.j2"
    dest: "{{ elasticsearch_combined.config_include_dir }}/elasticsearch.yml"
    owner: root
    group: root
    mode: 0644
  when:
    - not elasticsearch_combined.install_only

# https://docs.ansible.com/ansible/latest/modules/command_module.html
- name: Install plugins
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin install -b {{ item }}
  loop: "{{ elasticsearch_combined.install_plugins }}"
  when:
    - elasticsearch_combined.install_plugins

# http://docs.ansible.com/ansible/latest/systemd_module.html
- name: Ensure elasticsearch auto-starts
  systemd:
    name: elasticsearch
    enabled: yes

- name: Restart Elasticsearch
  systemd:
    name: "{{ elasticsearch_combined.daemon }}"
    state: restarted
  when:
    - not elasticsearch_combined.install_only

- name: Pause for Elasticsearch
  pause:
    seconds: 60
  when:
    - not elasticsearch_combined.install_only

- name: Restart Elasticsearch
  systemd:
    name: "{{ elasticsearch_combined.daemon }}"
    state: restarted
  when:
    - not elasticsearch_combined.install_only

# http://docs.ansible.com/ansible/latest/systemd_module.html
- name: Ensure that the service is running
  systemd:
    name: elasticsearch
    state: started
  when:
    - not elasticsearch_combined.install_only

- name: Wait for Elasticsearch to become available, on port 9200
  wait_for:
    port: 9200
    delay: 5
    timeout: 60000
  when:
    - not elasticsearch_combined.install_only
